MODEL:
  WEIGHTS: ''
compute_precision:
  grad_scaler: true
  teacher:
    backbone:
      sharding_strategy: SHARD_GRAD_OP
      mixed_precision:
        param_dtype: fp16
        reduce_dtype: fp16
        buffer_dtype: fp32
    dino_head:
      sharding_strategy: SHARD_GRAD_OP
      mixed_precision:
        param_dtype: fp16
        reduce_dtype: fp16
        buffer_dtype: fp32
    ibot_head:
      sharding_strategy: SHARD_GRAD_OP
      mixed_precision:
        param_dtype: fp16
        reduce_dtype: fp16
        buffer_dtype: fp32
  student:
    backbone:
      sharding_strategy: SHARD_GRAD_OP
      mixed_precision:
        param_dtype: fp16
        reduce_dtype: fp16
        buffer_dtype: fp32
    dino_head:
      sharding_strategy: SHARD_GRAD_OP
      mixed_precision:
        param_dtype: fp16
        reduce_dtype: fp32
        buffer_dtype: fp32
    ibot_head:
      sharding_strategy: SHARD_GRAD_OP
      mixed_precision:
        param_dtype: fp16
        reduce_dtype: fp32
        buffer_dtype: fp32
  auxiliary:
    auxiliary_decoder:
      sharding_strategy: SHARD_GRAD_OP
      mixed_precision:
        param_dtype: fp16
        reduce_dtype: fp16
        buffer_dtype: fp32
dino:
  loss_weight: 1.0
  head_n_prototypes: 65536
  head_bottleneck_dim: 256
  head_nlayers: 3
  head_hidden_dim: 2048
  koleo_loss_weight: 0.1
ibot:
  loss_weight: 1.0
  past_tea_ibot_loss_weight: 1.0
  future_tea_ibot_loss_weight: 1.0
  past_future_MSE_loss_weight: 1.0
  mask_change: false # whether to change mask ratio and mask prob during training
  mask_sample_probability: 0.5
  mask_sample_prob_range:
  - 0.5
  - 0.5
  mask_ratio_min_max:
  - 0.1
  - 0.5
  min_mask_ratio_range:
  - 0.1
  - 0.1
  max_mask_ratio_range:
  - 0.5
  - 0.5
  separate_head: false
  head_n_prototypes: 65536
  head_bottleneck_dim: 256
  head_nlayers: 3
  head_hidden_dim: 2048
train:
  debug_save: False # whether to save crops and attention maps
  debug_save_path: ./debug_save  # path to save crops and attention maps if debug_save is True
  batch_size_per_gpu: 64
  dataset: Kinetics
  dataset_path: Kinetics:split=TRAIN
  output_dir: .
  saveckp_freq: 20
  seed: 0
  num_workers: 10
  OFFICIAL_EPOCH_LENGTH: 936
  cache_dataset: true
  tb_log_freq: 100
  past_offset_range: 
  - 0.15
  - 0.25
  current_range: 
  - 0.3
  - 0.7
  future_offset_range: 
  - 0.15
  - 0.25
auxiliary:
  use_auxiliary: true  # whether to add the auxiliary branch to the model
  attn_mul: 4 # multiple on auxiliary_cross_attn in skip connection of the AuxiliaryAttentionBlock
  num_blocks: 1
  attention_head_num: 16  # the number of heads of cross-/self-attention in the decoder
  lr_mul: 0.1 # multiplier of the decoder's lr of the backbone's lr
student:
  arch: vit_small # vit_small/vit_base
  patch_size: 16
  drop_path_rate: 0.1
  layerscale: 1.0e-05
  drop_path_uniform: true
  pretrained_weights: ''
  ffn_layer: "mlp"
  block_chunks: 0
  qkv_bias: true
  proj_bias: true
  ffn_bias: true
  num_register_tokens: 4
  interpolate_antialias: true
  interpolate_offset: 0.0
teacher:
  momentum_teacher: 0.992
  final_momentum_teacher: 1
  warmup_teacher_temp: 0.04
  teacher_temp: 0.07
  warmup_teacher_temp_epochs: 30
optim:
  epochs: 400
  weight_decay: 0.04
  weight_decay_end: 0.4
  base_lr: 0.002 
  lr: 0.  # adaptive lr
  warmup_epochs: 10
  min_lr: 1.0e-06
  clip_grad: 3.0
  freeze_last_layer_epochs: 1
  scaling_rule: sqrt_wrt_1024
  patch_embed_lr_mult: 0.2
  layerwise_decay: 0.9
  adamw_beta1: 0.9
  adamw_beta2: 0.999
crops:
  global_crops_scale:
  - 0.32
  - 1.0
  local_crops_number: 8
  local_crops_scale:
  - 0.05
  - 0.32
  global_crops_size: 224
  local_crops_size: 96
evaluation:
  eval_period_iterations: 18720
